import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/store/Provider';
import Layout from '@/components/layout';
import AuthLoader from '@/components/Authloader';

export const metadata: Metadata = {
  title: 'Beelicious Bite - mini Pastry Store',
  description: 'Generated by create next app',

  icons: {
    icon: '/assets/img/logo/pastry-logo.jpg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthLoader>
            {' '}
            <Layout>{children}</Layout>
          </AuthLoader>
        </Providers>
      </body>
    </html>
  );
}
